### ISSUE TITLE
Specify import component

### ISSUE THREAD

**Issue by wouterbeek** [netwerk-digitaal-erfgoed/LDWizard#1]
Specifying and documenting the framework and its components:source data import functionality.

The import functionality for an optional existing script is covered in #17

**Comment by ivozandhuis** [comment]
Als ik het goed begrijp, komt het resultaat van deze activiteit terecht in par. 4.1 van de README.

**Comment by wouterbeek** [comment]
Klopt, al zitten we niet vast aan de eerste opzet in secties (maar dat zien we t.z.t.).

**Comment by wouterbeek** [comment]
@ivozandhuis Deze kun je al prima meenemen in je generieke review van het document.  Sectie 4.1 is nu ver genoeg voor detail feedback.
