### ISSUE TITLE
Ontwikkel interfaces voor GUI wizard component

### ISSUE THREAD

**Issue by thomasdegroot18** [netwerk-digitaal-erfgoed/LDWizard#10]
Een vijftal interfaces, volgens [issue 2](https://github.com/netwerk-digitaal-erfgoed/LDWizard/issues/2), als beschreven in stap A.
- [x]  Een interface om de brondata naar een genormaliseerde CSV om te zetten.
- [x]  Een interface om de IRI prefix in te stellen.
- [x] Een interface om op basis van een tekstuele invoer suggesties voor een klasse te geven.
- [x]  Een interface om de key kolom te identificeren.
- [x]  Een interface om op basis van een tekstuele invoer suggesties voor een eigenschap te geven.

**Comment by GerwinBosch** [comment]
Assigning it back to @wouterbeek, code is now live in netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard
