### ISSUE TITLE
Ontwikkel “Hello, World!” wizard

### ISSUE THREAD

**Issue by thomasdegroot18** [netwerk-digitaal-erfgoed/LDWizard#14]
De "Hello World!" wizard 
Deze Wizard heeft twee functies. 
 - Het fungeert als een eerste bruikbare test voor de wizard componenten die in de vorige issues zijn ontwikkeld. 
 - De "Hello World!" wizard is de basis template waar volgende projecten mee kunnen beginnen. Met behulp van deze wizard worden de basis interfaces uitgelegd die gebruikt kunnen maken van de 

De componenten voor de wizard zijn: 
- [x] Fungeert als een minimaal voorbeeld van hoe de wizard component technisch werkt.
- [x] Vormt de basis voor een programmeur om een bruikbare wizard op te baseren.
- [x] Biedt minimale implementaties voor de in 3 geïdentificeerde onderdelen, importeren van bronbestand, omzetten en uploaden.
- [x] Upload van csv bestanden.
- [x] Gebruikt een minimaal aantal transformatie interfaces.
- [x] Gebruikt een transformatie engine voor één van de ondersteunde ETL talen om RDF te maken.
- [x] Exporteert brondata, transformatie script, en RDF data.

**Comment by wouterbeek** [comment]
The latest changes from the NDE wizard were backported to the simple/generic Hello World wizard.  The latter is now published over at <https://github.com/netwerk-digitaal-erfgoed/LDWizard-HelloWorld>.  Closing this issue...
