### ISSUE TITLE
Ontwikkel NDE wizard

### ISSUE THREAD

**Issue by thomasdegroot18** [netwerk-digitaal-erfgoed/LDWizard#15]
In dit ticket beschrijven we hoe de ontwikkeling van de voorbeeld wizard van NDE eruit gaat zien.  
Deze wizard moet een voorbeeld zijn van hoe een geavanceerdere wizard werkt. Hierbij willen we gebruik maken van een aantal specifieke usecases die voor NDE bruikbaar zijn. De wizard kan worden om bronbestanden

De non exaustive list van componenten voor de wizard zijn: 
- [x] Fungeert als een voorbeeld van hoe een bruikbare wizard voor een specifiek domein geconfigureerd kan worden.
- [x] Moet toepasbaar zijn voor het omzetten van een daadwerkelijk bronbestand (eventueel na cleaning/preparatie).
- [x] Maakt RDF aan op basis van door de gebruiker gemaakte selecties in een simpele GUI.
- [x] Veronderstelt data uit het erfgoed domein.
- [x] Maakt gebruik van Schema.org ~~en het NDE termen netwerk~~.
- [x] Bevat een invoerveld om een IRI prefix in te stellen.
- [x] Bevat een zoekveld om een klasse in te stellen.
- [x] Bevat een combobox om een key kolom te selecteren.
- [x] Voor iedere kolom: bevat een combobox om een eigenschap toe te kennen.
- [x] Resterende functionaliteiten zoals in (D).

**Comment by wouterbeek** [comment]
De NDE LD Wizard is inmiddels beschikbaar op <https://github.com/netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard>.  Deze maakt nog geen gebruik van het NDE termen netwerk, omdat dit bedoelt is voor instantie termen / cel waardes.  Deze laatste zijn op dit moment nog niet beschikbaar binnen de LD Wizard.
