### ISSUE TITLE
language?

### ISSUE THREAD

**Issue by rlzijdeman** [netwerk-digitaal-erfgoed/LDWizard#16]
Hi guys, I would like to ask whether we could do documentation and sprint planning in English. I am very confident about the pickup of this tool beyond national borders. Moreover, within national borders several people working with CLARIAH, ODISSEI, eScience Center that could help contribute to LDWizard do not speak Dutch

**Comment by wouterbeek** [comment]
Good point, this is the first issue in English :-)  We will also write the document in English, unless there are objections from somebody.

**Comment by rlzijdeman** [comment]
Bam! First issue closed!!
