### ISSUE TITLE
Prototyping GUI components

### ISSUE THREAD

**Issue by thomasdegroot18** [netwerk-digitaal-erfgoed/LDWizard#19]
Before the actual implementation of the Graphical UI, we will use prototyping software to create mockups for the user interfaces of the product. Developing these mockups can create an earlier feedback cycle on the UI/UX aspect of the product.    

The technical components will not be implemented in this ticket. Here we design and discuss the how the user can use/interact with the product.

**Comment by wouterbeek** [comment]
These mockups are now included in the [design document](https://github.com/netwerk-digitaal-erfgoed/LDWizard/blob/master/docs/design.md).
