### ISSUE TITLE
Specificeer wizard GUI component

### ISSUE THREAD

**Issue by wouterbeek** [netwerk-digitaal-erfgoed/LDWizard#2]
Het vastleggen en documenteren van het raamwerk en haar componenten voor de wizard GUI component

  - [x] Het specificeren van het instellen van een IRI prefix.
  - [x] Het specificeren van het opzoeken en selecteren van één klasse voor alle rijen (`rdf:type`).
  - [x] Het specificeren van het identificeren van één kolom als key (subject term).
  - [x] Het specificeren van het opzoeken en selecteren van één eigenschap per kolom (predicaat term).
  - [ ] ~~Het specificeren van één of meer custom functies om object termen op te schonen (object term).~~

**Comment by ivozandhuis** [comment]
Als ik het goed begrijp, komt het resultaat van deze activiteit terecht in par. 4.2 van de README.

**Comment by ivozandhuis** [comment]
4.2.1.b / 4.2.2.b
Remove section, @vocab could be based on @base

4.2.1.c:
Continue
    The subject IRIs are not modified. Information in two or more rows will be merged into one RDF record.

4.2.1.h
Decision TBD

4.2.1.i
Is choosing an option? No data is no triple, I guess.

4.2.1.j
Is this too much Open Refine?

4.2.2.g
TBD

4.2.2.i and 4.2.2.j are not there.

**Comment by wouterbeek** [comment]
Het opschonen van cel waardes is niet geimplementeerd.  Deze opschoon acties moeten voorlopig worden uitgevoerd voordat de gegevens in LD Wizard worden ingeladen.
