### ISSUE TITLE
RMLEditor is a tool not a language

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/LDWizard#23]
[Section 4.3.1 in the Design Document](https://github.com/netwerk-digitaal-erfgoed/LDWizard/blob/master/docs/design.md#431-description-and-priority) refers to RMLEditor as a language, this is not correct this should be [RML](https://rml.io/specs/rml/). Check for others places too...

**Comment by thomasdegroot18** [comment]
This has been corrected in the latest version of the documentation <https://github.com/netwerk-digitaal-erfgoed/LDWizard/commit/90b5a51edab3ca8b79d818082f9830de0ac2c115>
