### ISSUE TITLE
Specificeer download/export component

### ISSUE THREAD

**Issue by wouterbeek** [netwerk-digitaal-erfgoed/LDWizard#3]
Het vastleggen en documenteren van de download/export component:

  - [x] Het specificeren van de export van het transformatie script.
  - [x] Het specificeren van het uitvoeren van de transformatie.
  - [x] Het specificeren van de export van de getransformeerde RDF data.

**Comment by ivozandhuis** [comment]
Als ik het goed begrijp, komt het resultaat van deze activiteit terecht in par. 4.3 van de README.
