### ISSUE TITLE
Specificeer upload/publish component

### ISSUE THREAD

**Issue by wouterbeek** [netwerk-digitaal-erfgoed/LDWizard#4]
Het vastleggen en documenteren van de upload/publish component:

  - [x] Het specificeren van de authenticatie tot een publicatie platform.
  - [x] Het specificeren van de publicatie locatie binnen het publicatie platform.
  - [x] Het specificeren van de upload van het bronbestand.
  - [x] Het specificeren van de upload van het transformatie script.
  - [x] Het specificeren van de upload van de getransformeerde RDF data.

**Comment by ivozandhuis** [comment]
Als ik het goed begrijp, komt het resultaat van deze activiteit terecht in par. 4.4 van de README.
