### ISSUE TITLE
sorry: Safari bug :(

### ISSUE THREAD

**Issue by rlzijdeman** [netwerk-digitaal-erfgoed/LDWizard#45]
Hi, when 
- in the column configuration / property configuration menu;
- inputting a (non-)recognized property and hitting enter or pressing the 'confirm button';
- ldwizard is reset and my data and changes lost

Was able to replicate this bug, but only in Safari 13.1.1 on macOS Catalina 10.15.5, but not Firefox 81.0 on the same OS.

**Comment by GerwinBosch** [comment]
Yep, from what I've gathered this probably has to do with the default behavior of HTML forms. Either setting one of the relevant attributes, or preventing default in the submit event
