### ISSUE TITLE
error on file format only when publishing data

### ISSUE THREAD

**Issue by rlzijdeman** [netwerk-digitaal-erfgoed/LDWizard#46]
[DutchMunicipalities1812-2012Spatio-Temporal_test.convert.txt](https://github.com/netwerk-digitaal-erfgoed/LDWizard/files/5310162/DutchMunicipalities1812-2012Spatio-Temporal_test.convert.txt)
Hi, whilst uploading my converted dataset to TriplyDB (the NDE instance), i received the following error: Unexpected <something from file> in line 7. I'm attaching a screenshot as well as csv and RATT file (if you wanted to study it in detail).

For now the main points seem to be:
- could this error be detected before the upload phase?
- where do I go / what do I do when I'm a user encountering such an issue?

ps: I changed the data file's and RATT conversion file's extensions from to .txt in order to be able to upload it here.

![Screenshot 2020-10-01 at 09 15 18](https://user-images.githubusercontent.com/3480446/94779375-22abed00-03c7-11eb-9bff-087899744187.png)

[DutchMunicipalities1812-2012Spatio-Temporal.txt](https://github.com/netwerk-digitaal-erfgoed/LDWizard/files/5310149/DutchMunicipalities1812-2012Spatio-Temporal.txt)

**Comment by wouterbeek** [comment]
The notation `\uXXXX` is legal in literals, but not in IRIs (there `%XX` should be used instead).  The issue may be that literal escaping is applied to export an IRI (or something along those lines).
