### ISSUE TITLE
unexplained space added to property uri

### ISSUE THREAD

**Issue by rlzijdeman** [netwerk-digitaal-erfgoed/LDWizard#48]
Hi,

To denote something of the property 'dbo:province', I copied this from Linked Open Vocabularies:
`http://dbpedia.org/ontology/province`

and pasted it in the property configuration field.

When uploading the data into a TriplyDB it breaks, because somehow a space was added in the property URI. I checked whether I did unintentionally did it myself, but there really seems to be no space in the path. 

when I selected something from the list, this issue did not occur: `schema:addressRegion`

Screenshots are attached
![Screenshot 2020-10-03 at 06 09 56](https://user-images.githubusercontent.com/3480446/94983066-bb657880-053f-11eb-891a-3b0233fa4fc9.png)
![Screenshot 2020-10-03 at 06 15 20](https://user-images.githubusercontent.com/3480446/94983085-d932dd80-053f-11eb-9c14-5528381c11fd.png)
![Screenshot 2020-10-03 at 06 15 07](https://user-images.githubusercontent.com/3480446/94983087-d9cb7400-053f-11eb-9798-5ca1d1397000.png)

**Comment by rlzijdeman** [comment]
I just had the same thing when I was adding `http://www.gemeentegeschiedenis.nl/amco/` as prefix (I checked, whether I did not make the mistake myself). 

Could it be related to the fact that it expects 5 characters (`https`) rather than four (`http`)?
![Screenshot 2020-10-03 at 06 58 29](https://user-images.githubusercontent.com/3480446/94983729-e94dbb80-0545-11eb-886c-7d1efbc81c0a.png)

**Comment by GerwinBosch** [comment]
@rlzijdeman  I think you might have added a space before the field (HTML doesn't like extra whitespace and will remove it in most cases). Fixed it by trimming these values before storing them
