### ISSUE TITLE
IRI conversion does not update after 'back' button used

### ISSUE THREAD

**Issue by rlzijdeman** [netwerk-digitaal-erfgoed/LDWizard#49]
Hi,

when converting a value to an IRI,
downloading the RDF,
hitting the back button,
changing the value-iri and hitting the confirm button,
and next downloading the RDF,
still seems to provide the first value2IRI conversion, not the updated one.

**Comment by GerwinBosch** [comment]
Thanks for the report,

(Un)fortunately I am not able to reproduce this, please reopen the issues if this still occurs
