### ISSUE TITLE
Specificeer brondata formaten

### ISSUE THREAD

**Issue by wouterbeek** [netwerk-digitaal-erfgoed/LDWizard#5]
Het vastleggen en documenteren van de te gebruiken formaten en transformaties:

Het specificeren van het brondata formaat (een breed gebruikt spreadsheet formaat, aandachtspunt: toegestane karakters, aandachtspunt: aanwezigheid van header rij).

**Comment by ivozandhuis** [comment]
Als ik het goed begrijp, komt het resultaat van deze activiteit terecht in par. 4.1 van de README.

**Comment by wouterbeek** [comment]
I'm moving the discussion on which CSV format(s) to support from `README.md` to this issue (the outcome of this will be placed in the `README.md` later):

We must determine which CSV format(s) we support.  We must consider the following format dimensions:

- **Cell separator**: `,` (comma) or `;` (semi-colon).  The semi-colon is popular when cells commonly contains comma's and are not delimited by double quotes.  Also, in some locates the comma is used as the decimal separator (e.g., the Dutch locale).  While the semi-colon can appear inside cells too, it is less common.

- **Cell quoting**: some CSV formats use `"` (double quote) in order to delimit field values.  Such values 

- **Line separator**: `CRLF`, `CR`, and/or `LF`.

-  **Character set**: UTF-8

- **Special characters**: Maybe requirements from TriG (= the format that we convert towards).

Furthermore, what does and does not constitute a valid CSV file can be decided on the following levels:

```
<dl>
  <dt>Interface level</dt>
  <dd>The CSV format is part of the LD Wizard Interface.  All LD Wizard Applications must use the same CSV format.</dd>
  <dt>Application level</dt>
  <dd>The CSV format is specified by the developer of an LD Wizard Application.  This allows for more flexibility, but can also be confusing when users of one application except another application to be have similarly.</dd>
  <dt>User level</dt>
  <dd>The user of an LD Wizard Application is able to specify the CSV format.  This gives more control to the user, but also assumes the users understands which CSV formats there are and how they can be specified.</dd>
</dl>
```

Argument for going with the *Application level*: A developer may have more information about which CSV format is commonly used in a particular domain or use case.  The domain expert can also help if users have the incorrect CSV, and help them transform the CSV file.

**Comment by wouterbeek** [comment]
Microsoft Excel (latest version) seems to be fully standard compliant when exporting to CSV:

```
"a""b","c,d",e;f
```

**Comment by wouterbeek** [comment]
The specification at the application and user level are dropped: specification at the interface level is easy to achieve in this case.

**Comment by wouterbeek** [comment]
@ivo Deze is ook ver genoeg, eveneens Sectie 4.1.

**Comment by ivozandhuis** [comment]
* 4.1.1a Do we decide to accept non-CSV tabular data? It does not state this explicitely.
* 4.1.3 "Specify a soft limit for the file size" What do you mean with "soft"?
