### ISSUE TITLE
add a 'reset' / 'start all over' button

### ISSUE THREAD

**Issue by rlzijdeman** [netwerk-digitaal-erfgoed/LDWizard#50]
Hi, 

After having converted one csv to LOD, one ofcourse, wants do another! But there is no 'again' / 'reset' / 'start over' button.

Perhaps clicking on the 'Erfgoedwizard' text, could do that (obviously with a 'are you sure, all will be lost'-warning).

![Screenshot 2020-10-03 at 06 37 51](https://user-images.githubusercontent.com/3480446/94983468-57dd4a00-0543-11eb-8a51-2bbca5103c19.png)

**Comment by mightymax** [comment]
See https://github.com/netwerk-digitaal-erfgoed/LDWizard-Core/pull/57
