### ISSUE TITLE
Publish step does not upload CSV file

### ISSUE THREAD

**Issue by wouterbeek** [netwerk-digitaal-erfgoed/LDWizard#52]
# Observed

When publishing a dataset from LD Wizard, the following assets are *always* uploaded:

  - `{data}.rml.ttl`
  - `{data}.csv-metadata.json`
  - `{data}.convert.ts`

The following asset is *sometimes* uploaded:

  - `{data}.csv`

# Expected

The standardized CSV file (`{data}.csv`) to *always* be uploaded.

# Steps to reproduce

I have not found reproducible steps for this issue yet.  I am able to observe this though, by going back and forth through the LD Wizard steps and maybe refresh the tab and/or maybe upload a new CSV source file in the meantime.

**Comment by GerwinBosch** [comment]
Hmm I can't seem to reproduce this either. This might have been fixed in the migration to the core-script. Otherwise I think it might be fixed by either #62, or upping the TriplyDBjs dep in #63.

Please re-open it if you see it again!
