### ISSUE TITLE
Row-based identifiers are count-by-0

### ISSUE THREAD

**Issue by wouterbeek** [netwerk-digitaal-erfgoed/LDWizard#57]
# Observation

When choosing the row number for identification, row numbers start at 0 in the generated linked data.

# Expected

Row numbers to start at 1 in the generated linked data, because it is more common outside computer science.

# Steps to reproduce

1. Transform a CSV while only using the default settings.  This will also use the row numbers for identification.
2. Download the RDF and notice that the first subject term IRI using identifier 0.

**Comment by mightymax** [comment]
Looks like this is no longer the behaviour using the current repository. I've tried to reproduce this issue, but my first identifier is `<https://data.netwerkdigitaalerfgoed.nl/b69dbe/id/1>`. If someone can confirm this issue can be closed.

**Comment by EnnoMeijers** [comment]
You are right, same result for me!
