### ISSUE TITLE
Add installation of 'http-server'

### ISSUE THREAD

**Issue by ivozandhuis** [netwerk-digitaal-erfgoed/LDWizard#58]
I needed to install the cli http-server that is used to start the application.
```bash
sudo npm install --global http-server
```
Shouldn't that be added to the documentation?

**Comment by wouterbeek** [comment]
Any HTTP server will work.  There are many different servers out there, but it does not hurt to mention this particular HTTP server in the documentation.

**Comment by wouterbeek** [comment]
I have added the installation of this particular HTTP server to the documentation: [link](https://github.com/netwerk-digitaal-erfgoed/LDWizard#2a-run-locally)

Can you check the description there?

**Comment by GerwinBosch** [comment]
Assuming this can be closed

**Comment by ivozandhuis** [comment]
Adjusted a sentence in this commit: 77f1d989b45feaea9bed8d8da864cdfa616e4700
