### ISSUE TITLE
Specificeer mappings naar ETL talen

### ISSUE THREAD

**Issue by wouterbeek** [netwerk-digitaal-erfgoed/LDWizard#6]
Het vastleggen en documenteren van de te gebruiken formaten en transformaties:

Het specificeren van mappings naar ten minste een of meer bestaande ETL talen:

  - [ ] COW
  - [ ] RML
  - [ ] RATT

**Comment by ivozandhuis** [comment]
Kiezen we er twee uit het rijtje van drie, of bedoel je dat we er drie kiezen?

**Comment by ivozandhuis** [comment]
Ik interpreteer CoW als de tool die een transformatie mogelijk maakt met een transformatie-template in CSV-for-the-web formaat. Zie ik dat goed?

**Comment by rlzijdeman** [comment]
[CoW](https://github.com/clariah/cow/wiki) is een csv naar RDF converter. CoW genereert een json template op basis van de CSV, waar een gebruiker al dan niet bewerkingen op uit kan voeren. De (on)bewerkte template wordt vervolgens naar RDF geconverteerd.  In het proces is zoveel mogelijk gehouden met [CSV on the Web](https://www.w3.org/TR/tabular-data-primer/), maar is dat ons niet altijd gelukt. Ik hoop dat dit je vraag beantwoordt. Overigens volgens mij is het beter de issues in het engels te doen

**Comment by wouterbeek** [comment]
@rlzijdeman Goed punt, we gaan nieuwe issues in het Engels aanmaken :-)

@ivozandhuis We moeten hierin nog een keuze maken.  CoW wordt al veel gebruikt binnen het erfgoed domein (Clariah), dus dat kan een goede eerste keuze zijn.  (En andere ETL formaten mogelijk later toevoegen.)

**Comment by EnnoMeijers** [comment]
Ik zou graag ook de SPARQL CONSTRUCT optie in beeld willen houden dit vraagt geen specifiek transformatie proces en is dus eenvoudig te implementeren aangezien we al uitgaan van de beschikbaarheid van een sparql endpoint.

**Comment by wouterbeek** [comment]
@EnnoMeijers Maak je in het geval van SPARQL CONSTRUCT ook gebruik van een RDF input bestand i.p.v. een CSV input bestand?

**Comment by EnnoMeijers** [comment]
Inderdaad, het uitgangspunt is altijd een basale RDF representatie die getransformeerd en eventueel verrijkt wordt via INSERT of CONSTRUCT queries.

**Comment by wouterbeek** [comment]
Wel interessant om mee te nemen, maar niet voor de CSV-naar-RDF conversie?  Want de wizard maakt assumpties over kolommen, rijen, e.d. die niet in een RDF bestand voorkomen.  Of zit ik verkeerd te denken?

**Comment by EnnoMeijers** [comment]
Inderdaad, relevant als de wizard voor de LD specialist, niet voor de eerste verwerking.

**Comment by wouterbeek** [comment]
Separated SPARQL CONSTRUCT support into a separate issue: #18

**Comment by thomasdegroot18** [comment]
Instead of developing a new ETL-tool we will use an existing ETL-tool to execute the transformation step. We decided to use a client based transformation tool (RML/RATT) as the tool to transform the csv to RDF. Which of the tools that are available will be decided when research about the performance and adaptability will be finished.

The mapping for ETL scripts will happen from the choice of ETL-transformation, to the other tools. 

Our preference on how to reuse the transformation script will be discussed in issue: <https://github.com/netwerk-digitaal-erfgoed/LDWizard/issues/17>

**Comment by thomasdegroot18** [comment]
For now I've been looking into handling the bindings between the three languages.

To keep it simpler for now I will make a few assumptions about the data for now. But some/all of these restrictions could be removed in a later point of the process. 

 - We assume that there is only one subject in the script/csv/template
 - We assume that the description about the subject in the script is handled as high as possible in the template.  

Step 1: Find the subject in the row, either the rownumber or the predefined column, set as subject.
Step 2: If needed convert the subject to a proper IRI.
Step 3: Move from left to right to the column, starting from the first/second depending on the location of the subject.
Step 4: Skip the column if the column is not mentioned in RATT, RML, or set to skip in COW.
Step 5a: Clean the value in the column we do want to parse, for now with template based cleaning.
Step 5b: Set the datatype of the column we do want to parse. If the object is an IRI, make sure that we set it correctly.
Step 5c: (Set/Parse column as predicate) and link the subject and the object together with the correct predicate.
Step 6: Move back to step 3, until it the end of the table is reached. 

With this way of stepping through the columns and conversion, we can have a better guarantee that the transformation between the 3 languages can be successful if all three languages follow these steps.

**Comment by ivozandhuis** [comment]
Decision?

**Comment by wouterbeek** [comment]
The first set of supported ETL languages are RML, CoW and RATT (internal format).
