### ISSUE TITLE
Error using termennetwerk

### ISSUE THREAD

**Issue by ivozandhuis** [netwerk-digitaal-erfgoed/LDWizard#60]
When a CSV column includes at least one empty cell, then perform a cell-based transformation (e.g., Termennetwerk in <https://ldwizard.netwerkdigitaalerfgoed.nl>) emits the following error:

```
"query" is not allowed to be empty: {"response":{"data":{"terms":null},"errors":[{"message":"\"query\" is not allowed to be empty","locations":[{"line":3,"column":5}],"path":["terms"]}],"status":200},"request":{"query":"\n query Terms($query: String!) {\n terms(\n sources: [\"http://vocab.getty.edu/aat/sparql\", \"https://data.cultureelerfgoed.nl/PoolParty/sparql/term/id/cht\"]\n query: $query\n ) {\n source {\n name\n }\n result {\n __typename\n ... on Terms {\n terms {\n uri\n }\n }\n ... on Error {\n message\n }\n }\n }\n }\n","variables":{"query":""}}}
```

### Steps to reproduce

1. Upload the following CSV file to <https://ldwizard.netwerkdigitaalerfgoed.nl>.

     ```
     a,b
     Amsterdam,1
     ,2
     ```

2. Use the Termennetwerk transformation for column "a".
3. Click on "Next" and observe the error.

**Comment by wouterbeek** [comment]
@ivozandhuis Thanks for reporting.  I have added reproducibility steps to your issue.

**Comment by GerwinBosch** [comment]
Fixed in https://github.com/netwerk-digitaal-erfgoed/LDWizard-ErfgoedWizard/commit/de1d8d46ca818167913f7f829f1df3ec53e27445
