### ISSUE TITLE
Unable to perform cell-based transformation twice

### ISSUE THREAD

**Issue by wouterbeek** [netwerk-digitaal-erfgoed/LDWizard#61]
When I run the same cell-based transformation twice, I sometimes observe the following error:

```
Cannot read property 'length' of undefined
```

### Steps to reproduce

1. Upload <https://data.labs.kadaster.nl/hack-a-lod/stolpersteiner/assets/6009685c1dea810363ce3ba6> in <https://ldwizard.netwerkdigitaalerfgoed.nl>.
2. Use Termennetwerk cell-based transformation on the death place column.
3. Click "Next".
4. Click "Previous".
5. Click "Next" again.  Observe the above error.

**Comment by GerwinBosch** [comment]
@wouterbeek I am not able to reproduce this at the moment, please re-open if it still happens!
