### ISSUE TITLE
Error when uploading twice

### ISSUE THREAD

**Issue by wouterbeek** [netwerk-digitaal-erfgoed/LDWizard#62]
When I upload to an existing dataset that was already used to upload to from LD Wizard in the past I get the following error:

```
Tried to add asset 'example.convert.ts' to dataset wouter/test, but an asset with that name already exists.
```

When I change upload to use a new dataset the LD Wizard (sometimes?) resets to the home page.

# Steps to reproduce

1. Upload the results from LD Wizard to a new dataset.
2. Use a new LD Wizard to upload new results to the same dataset.  Notice the above message.
3. Create a new dataset (with the intention of uploading to it) and notice that the LD Wizard goes to the home page / step 1.

**Comment by GerwinBosch** [comment]
Will be part of the next release
