### ISSUE TITLE
Use filename for RDF result

### ISSUE THREAD

**Issue by ivozandhuis** [netwerk-digitaal-erfgoed/LDWizard#67]
# Observation
If you download the enriched csv, cow, ratt or rml file the name of the file is the name of the original uploaded {orgfilename}.csv file. The RDF file you download is called 'result.nt'.

# Expected
{orgfilename}.nt

**Comment by mightymax** [comment]
@ivozandhuis do you mind checking out my branch and confirm that your expected behaviour is there?

**Comment by ivozandhuis** [comment]
@mightymax Is it easy for you to deploy it somewhere I can check?

**Comment by mightymax** [comment]
Sure, but let me know as soon as you can confirm this issues is resolved, so I can shut it down: 
https://www.lindeman.nu/ldwizard/

**Comment by ivozandhuis** [comment]
It works! Cool. Thank you. You can take it down.

**Comment by mightymax** [comment]
see https://github.com/netwerk-digitaal-erfgoed/LDWizard-Core/pull/54
