### ISSUE TITLE
Error after using upload-to-triple-store

### ISSUE THREAD

**Issue by wouterbeek** [netwerk-digitaal-erfgoed/LDWizard#68]
When I use the upload-to-triple-store functionality, I get an error whenever I use the LD Wizard again later.

The error is as follows:

![Screenshot from 2021-03-26 13-59-22](https://user-images.githubusercontent.com/1685012/112635062-a48f4700-8e3b-11eb-8136-6dd69b6f772f.png)

# Steps to reproduce

1. Use the upload-to-triple-store functionality from the 3rd LD Wizard page/step.
2. Go though the LD Wizard again, starting at the 1st page/step.
3. Once you reach the 3rd page/step again, the above error appears.

**Comment by ivozandhuis** [comment]
Has the kadaster context something to do with it?

**Comment by GerwinBosch** [comment]
Will include this in the next release
