### ISSUE TITLE
Upload to triple store does not work

### ISSUE THREAD

**Issue by wouterbeek** [netwerk-digitaal-erfgoed/LDWizard#69]
When I try to upload to the triple store from the 3rd page/step, the upload does not work ~50% of the time.

Instead, the LD Wizard seems to reset without error and show the 1st page/step.  All user configurations are also reset.

# Steps to reproduce

1. Try to use the upload-to-triple-store functionality once or twice.

**Comment by ivozandhuis** [comment]
Would that be the ldwizard.netwerkdigitaalerfgoed.nl instance? That might be of importance?

**Comment by GerwinBosch** [comment]
Might be resolved with  https://github.com/netwerk-digitaal-erfgoed/LDWizard-Core/commit/1d18ed83e94bcb3e42a44801474ae548e894c679

**Comment by wouterbeek** [comment]
@GerwinBosch I think you indeed fixed it!  I no longer see this issue :-)
