### ISSUE TITLE
Specificeer het RDF resultaat formaat

### ISSUE THREAD

**Issue by wouterbeek** [netwerk-digitaal-erfgoed/LDWizard#7]
Het vastleggen en documenteren van de te gebruiken formaten en transformaties:

Het specificeren van het gebruikte RDF formaat.

**Comment by ivozandhuis** [comment]
Is dit de keuze voor het RDF-formaat bij download/export of upload/publish? En is het beperkt tot precies een formaat of kan de gebruiker/ontwikkelaar van de wizard hierin kiezen?

**Comment by wouterbeek** [comment]
Goede vraag, we moeten ten minste 1 formaat vastleggen wat kan worden gedownload naar een lokale file, en/of kan worden geupload naar een triple store.

Misschien is het goed om de keuze voor meerdere formaten als een uitbreiding te zien (en die uitbreidbaarheid vervolgens mogelijk/makkelijk te maken).

**Comment by rlzijdeman** [comment]
FWIW my thoughts:
As a researcher I like nquads because of the 4th piece of info for provenance, but in readability nothing excels like turtle. 
[CoW](https://github.com/clariah/cow/wiki/) contains btw some code to deliver virtually any format so that might be reusable or this is already a first use case for using LDWizard in tandem with RATT, RMLEditor, CoW.

**Comment by wouterbeek** [comment]
@rlzijdeman Good points, let me split this into different functionality dimensions.

Completeness:
  - TriG, N-Quads, JSON-LD are able to include the graph component, so are able to return complete RDF.
  - Turtle, N-Triples, RDF/XML are not able to include the graph component, so are not able to return complete RDF.
  - However, initially we will not allow the graph component to be set in LD Wizard, since this is normally thought of as an expert feature.

Readability:
  - Turtle and TriG are based on N3, so are made with readability in mind.
  - N-Quads and N-Triples are also based on N3, but with batch processing in mind.
  - RDF/XML and JSON-LD are based on XML and JSON respectively.  They try their best within these base formats, but are also limited by them.  This makes them less readable than Turtle/TriG and also less batch processable than N-Quads/N-Triples.

Technological simplicity:
  - N-Quads and N-Triples are simplest to process algorithmically because of their minimal syntax.  Within these formats, it is possible to specify a format that can guarantee a one-to-one correspondence between triples and lines.  This makes it easy to process, and also makes it easy to skip erroneous triples (= skip to the next line).
  - TriG and Turtle require a more complex parser.
  - RDF/XML and JSON-LD require a full XML or JSON parser respectively, in addition to the RDF/XML and JSON-LD specific parts.

**Comment by wouterbeek** [comment]
@rlzijdeman Can you share a small snippet of the kind of Turtle that CoW exports?  The benefit of using Turtle or TriG also requires that the RDF generator makes optimal use of the abbreviations that these formats allow.

**Comment by ivozandhuis** [comment]
chosen: TriG, see [design 2.4.3.](https://github.com/netwerk-digitaal-erfgoed/LDWizard/blob/master/docs/design.md#243-publication-platform-assumptions) and [design 4.3.1](https://github.com/netwerk-digitaal-erfgoed/LDWizard/blob/master/docs/design.md#431-description-and-priority)
