### ISSUE TITLE
Bug in IRI Prefix transformation <NL>

### ISSUE THREAD

**Issue by kad-wenner** [netwerk-digitaal-erfgoed/LDWizard#78]
- Het lijkt erop dat de verrijking door middel van IRI Prefix Transformation niet werkt. Dit heb ik getest door middel van de waarden https://bag2.basisregistraties.overheid.nl/bag/id/object/NL.IMBAG.Nummeraanduiding. en  https://bag2.basisregistraties.overheid.nl/bag/id/object/ 

**N.B.** Deze observaties zijn gedaan op basis van de Kadaster variant (de Geodatawizard) beschikbaar op https://labs.kadaster.nl/demonstrators/geodatawizard/. Gewenste functionaliteit hoort echter meer thuis bij de LDWizard core. Fout lijkt generiek aanwezig te zijn.

**Comment by mightymax** [comment]
Beste @kad-wenner, kun je dit issue wat verder toelichten? Ik heb geprobeerd je probleem te reproduceren, maar krijg zelf wel de waardes die ik zou verwachten. Misschien kun je een stap-voor-stap script uitwerken en dan beschrijven wat je verwachtte output is v.s. de verkregen output?

**Comment by wouterbeek** [comment]
I also cannot reproduce this bug.  I do notice that IRI prefix transformation does not perform URI resolution (which is what I expected it to do).  I have created #88 for this.

@kad-wenner Feel free to reopen with more information in case we misunderstood your issue.
